= RESTful API
({bversion}-{bnumber})
Heiko Scherrer;
:doctype: book
:toc:
:sectanchors:
:sectlinks:
:toclevels: 2
:source-highlighter: highlightjs

[[overview]]
= Overview

This guide describes the RESTful API of the OpenWMS.org Transportation module and its usage. Some general terms and definitions
are explained and declared in the first part of the document whereas in the second part the usage of the API is shown in
a more use-case-driven approach.

[[resources-to]]
== TransportOrders

API to deal with `TransportOrders`.

[[resources-to-create]]
=== Create a new TransportOrder

At least the `Barcode` of the `TransportUnit` that needs to be moved and the `Target` destination must be given to create a new `TransportOrder`.
In this example we also define the `Priority` of the `TransportOrder`.

==== Request to move TransportUnit to a Location

include::{generated}/to-create/curl-request.adoc[]

If the `TransportOrder` has been created successfully, the server responds with status code `201` and returns the URI of the created
`TransportOrder` in the `LOCATION` header.

==== Response if created

include::{generated}/to-create/http-response.adoc[]

The URI can be used to lookup the created `TransportOrder` by it's persistent key. A `GET` request would look like this:

==== Lookup the created TransportOrder

include::{generated}/to-create-and-get/curl-request.adoc[]

and the server returns the representation of the created `TransportOrder`

include::{generated}/to-create-and-get/http-response.adoc[]

==== Fails to create a TransportOrder
The creation of a new `TransportOrder` may fail for several reasons. At first the `TransportUnit` with the given `Barcode` must already exist.
If no `TransportUnit` exists, the server responds with a http status code `404` (Not Found):

include::{generated}/to-create-uk-to/http-response.adoc[]

Another reason why the server cannot create a requested `TransportOrder` may be, because the Targert

=== Changing TransportOrders

Already existing and active `TransportOrders` can be redirected to a new `Target`. This redirection happens through an PATCH request
where the API expects the partial structure of the `TransportOrder` as request body. Sending a PATCH request allows also changing the
`Priority` of an `TransportOrder`.

==== Redirect to new Target
Redirect the `TransportOrder` with the given persistent key to a new `Target`

include::{generated}/to-patch-target-blocked-loc/curl-request.adoc[]

==== Change Priority
The follow example shows the request to decrease the `Priority` of an existing `TransportOrder` identified by the given persistent key to `NORMAL`.
Notice that the `TransportOrder` does not need to be started yet.

include::{generated}/to-patch-priority-ok/curl-request.adoc[]

On a successfully executed `PATCH` request the server responds with a http status code `204`

include::{generated}/to-patch-priority-ok/http-response.adoc[]

If the server does not accept the passed `Priority` level the response status is `400` (Bad Request),

include::{generated}/to-patch-priority-with-null/http-response.adoc[]

